apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front
  namespace: '{{ .Values.namespace }}'
  labels:
    app: chat_front
    type: roost-example
spec:
  replicas: {{ .Values.services.chat_front.replicaCount }}
  selector:
    matchLabels:
      app: chat_front
      type: roost-example
  template:
    metadata:
      labels:
        app: chat_front
        type: roost-example
    spec:
      containers:
        - name: chat-front
          image:
            '{{- printf "%s/%s:%s" .Values.registry
            .Values.services.chat_front.imageName .Values.tag -}}'
          imagePullPolicy: '{{ .Values.imagePullPolicy }}'
          stdin: true
          tty: true
          env:
            - name: CHAT_SERVICE_HOST
              value:
                'http://{{ .Values.namespace }}.{{
                .Values.services.chat_svc.serviceName }}.{{ .Values.clusterIP
                }}.{{ .Values.clusterDomain }}'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.services.chat_front.serviceName }}'
  namespace: '{{ .Values.namespace }}'
  labels:
    app: chat_front
    type: roost-example
spec:
  ports:
    - port: {{ .Values.services.chat_front.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: chat_front
    type: roost-example
