name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: 
        echo ${{ github.ref_name }}
        echo ${{ github.base_ref }}
        echo ${{ github.head_ref }}
        echo ${{ github.ref_type }}
        echo ${{ github.ref }}
        echo $GITHUB_REF_NAME
        echo $GITHUB_REF
